### ISSUE TITLE
特征点丢失的问题

### ISSUE THREAD

**Issue by y3715645** [chenjianqu/ORB_SLAM3_Mask#2]
作者你好，代码我已调试通过，但在运行数据集的过程中断断续续出现特征点全部丢失导致跟踪失败的问题，不知道是什么原因呢？希望能得到你的回复

**Comment by 33ShuoT** [comment]
大佬，请问你是怎么运行出来的，我运行数据集会报错："./rgbd_dataset_freiburg3_sitting_static/mask/seg_label_1341845688.561749.pt" does not exist
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.12) /home/shuo/opencv-3.4.12/modules/highgui/src/window.cpp:382: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'imshow'
